/*** Compiler Front-End Test automatically generated by the BNF Converter ***/
/*                                                                          */
/* This test will parse a file, print the abstract syntax tree, and then    */
/* pretty-print the result.                                                 */
/*                                                                          */
/****************************************************************************/
#include <stdio.h>
#include <string.h>
#include "Parser.H"
#include "FrontEnd.H"
#include "Absyn.H"
#include "Printer.H"
#include "LLVM.H"
#include <regex>
#include <iostream>
#include <fstream>

void usage() {
  printf("usage: Call with one of the following argument combinations:\n");
  printf("\t--help\t\tDisplay this help message.\n");
  printf("\t(no arguments)	Parse stdin verbosely.\n");
  printf("\t(files)\t\tParse content of files verbosely.\n");
  printf("\t-s (files)\tSilent mode. Parse content of files silently.\n");
}

int main(int argc, char ** argv)
{
  FILE *input;
  int quiet = 0;
  char *filename = NULL;

  if (argc > 1) {
    if (strcmp(argv[1], "-s") == 0) {
      quiet = 1;
      if (argc > 2) {
        filename = argv[2];
      } else {
        input = stdin;
      }
    } else {
      filename = argv[1];
    }
  }

  if (filename) {
    input = fopen(filename, "r");
    if (!input) {
      usage();
      exit(1);
    }
  } else input = stdin;
  /* The default entry point is used. For other options see Parser.H */
  Program *parse_tree = pProgram(input);
  if (parse_tree)
  {
    StaticAnalyzer *p = new StaticAnalyzer();
    try {
      p->analyze(parse_tree);
      std :: cerr << "OK\n";
      LLVM *llvm = new LLVM(p->env_of_classes);
      
      std :: ofstream output;
      std :: string name = filename;
      std :: string new_bc_name = name.substr(0, name.find_last_of('.')) + ".bc";
      std :: string new_ll_name = name.substr(0, name.find_last_of('.')) + ".ll";
      output.open(new_ll_name);
      output << llvm->run(parse_tree);
      output.close();
      system(("llvm-as -o " + new_bc_name + " " + new_ll_name).c_str());
      system(("llvm-link -o " + new_bc_name + " ./lib/runtime.bc " + new_bc_name).c_str());

      exit(0);
    }
    catch(front_end_exception &e) {
      std :: cerr << "ERROR\n";
      PrintAbsyn *p2 = new PrintAbsyn(e.msg, e.erronous_statement);
      std :: cerr << p2->print(parse_tree) << "\n";
      exit(-1);
    }
    return 0;
  }
  return -1;
}

